package com.kodilla.rps;

public enum GamePrintSelection {
    GAME_MENU_PRINT_LOGO_PRINT,
    GAME_MENU_PRINT_OPTIONS,
    GAME_MENU_PRINT_SUBMENU_OPTIONS,
    GAME_MENU_PRINT_EXIT,
    GAME_MENU_PRINT_PROGRAM_EXIT_MESSAGE_GAME,
    GAME_MENU_PRINT_SELECTION_DEFAULT,
    GAME_MENU_PRINT_INPUT_DATA,
    GAME_MENU_PRINT_SELECTION_DEFAULT_SUBMENU
}
