package com.kodilla.rps;

public enum GamePrinterOptions {
    GAME_PRINTER_OPTIONS_KAMIEN,
    GAME_PRINTER_OPTIONS_PAPIER,
    GAME_PRINTER_OPTIONS_NOZYCE,
    GAME_PRINTER_OPTIONS_NEW,
    GAME_PRINTER_OPTIONS_EXIT,
    GAME_PRINTER_OPTIONS_PLAYER_1,
    GAME_PRINTER_OPTIONS_PLAYER_2,
    GAME_PRINTER_OPTIONS_WINS,
    GAME_PRINTER_OPTIONS_LOST,
    GAME_PRINTER_OPTIONS_REMIS
}
